version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: hurrinet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yadmon13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=hurrinet_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yadmon13
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=hurrinet.settings
      - PYTHONPATH=/app/hurrinet
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
